// <auto-generated />
namespace WebApplication_trining.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dddo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dddo));
        
        string IMigrationMetadata.Id
        {
            get { return "202007311541408_dddo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
